name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t softness-predictor:latest .

      - name: Run tests
        run: |
          docker run -d -p 8000:8000 --name test-container softness-predictor:latest
          sleep 5
          curl --fail http://localhost:8000/health
          docker stop test-container